version: '3'

services:

  eureka-server-web:
    image: eureka-server-web-image
    build:
      context: ./EurekaServerApp
    ports:
      - 8761:8761    
    volumes:
      - /data/eureka-server
    restart: always
      
  product-service-db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product_service
      - MYSQL_USER=prasad
      - MYSQL_PASSWORD=prasad
    volumes:
      - /data/product_mysql
        
  review-service-db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product_review
      - MYSQL_USER=prasad
      - MYSQL_PASSWORD=prasad
    volumes:
      - /data/review_mysql 

  product-service-web:
    image: product-service-web-image
    build:
      context: ./ProductService/      
    environment:
      - DB_HOST=product-service-db
      - DB_USER=prasad
      - DB_PWD=prasad
      - EUREKA_HOST=eureka-server-web
    depends_on:    
      - product-service-db
      - eureka-server-web      
    ports:
      - 8082:8082
    volumes:
      - /data/product-review
    restart: always      
      
  review-service-web:
    image: review-service-web-image
    build:
      context: ./ProductReview
    environment:
      - DB_HOST=review-service-db
      - DB_USER=prasad
      - DB_PWD=prasad
      - EUREKA_HOST=eureka-server-web
    depends_on:
      - review-service-db
      - eureka-server-web
    ports:
      - 8083:8083
    volumes:
      - /data/product-review
    restart: always

  zipkin-service-web:
    image: zipkin-service-web-image
    build:
      context: ./Zipkin/
    environment:
      - EUREKA_HOST=eureka-server-web
    depends_on:
      - eureka-server-web
    ports:
      - 9411:9411
    volumes:
      - /data/zipkin-service
    restart: always

  zuul-service-web:
    image: zuul-service-web-image
    build:
      context: ./Zuul_ApiGateway/
    environment:
      - EUREKA_HOST=eureka-server-web
    depends_on:
      - eureka-server-web      
    ports:
      - 9999:9999
    volumes:
      - /data/zuul-service
    restart: always    


          