version: '3'

services:

  eureka-server-web:
    container_name: eureka_container
    hostname: eureka_host
    image: eureka-server-web-image
    build:
      context: ./EurekaServerApp
    ports:
      - 8761:8761    
    volumes:
      - /data/eureka-server    
      
  product-service-db:
    container_name: product_db_container
    hostname: product_db_host
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product_service
      - MYSQL_USER=prasad
      - MYSQL_PASSWORD=prasad
    volumes:
      - /data/product_mysql

  review-service-db:
    container_name: review_db_container
    hostname: review_db_host
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=product_review
      - MYSQL_USER=prasad
      - MYSQL_PASSWORD=prasad
    volumes:
      - /data/review_mysql 
  
    
  product-service-web:
    container_name: product_web_container
    image: product-service-web-image
    build:
      context: ./ProductService/      
    environment:
      - DB_HOST=product_db_container
      - DB_USER=prasad
      - DB_PWD=prasad
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server-web:8761/eureka      
    depends_on:    
      - product-service-db
      - eureka-server-web
    links:    
      - product-service-db
      - eureka-server-web     
    ports:
      - 8082:8082
    volumes:
      - /data/product-review
          
              
  review-service-web:
    container_name: review_web_container
    image: review-service-web-image
    build:
      context: ./ProductReview
    environment:
      - DB_HOST=review_db_container
      - DB_USER=prasad
      - DB_PWD=prasad
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server-web:8761/eureka
    depends_on:
      - review-service-db
      - eureka-server-web
    links:
      - review-service-db
      - eureka-server-web
    ports:
      - 8083:8083
    volumes:
      - /data/product-review
            
